name: pybalmorel
channels:
  - conda-forge
dependencies:
  - python >= 3.9
  - pandas >= 2.1.4 
  - matplotlib >= 3.9.0 
  - geopandas >= 0.14.4 
  - ipywidgets >= 8.1.3
  - ipykernel
  - pip
  - pip:
    - gamsapi[transfer] >= 45.0.0 
    - pybalmorel